### ISSUE TITLE
Define tests

### ISSUE THREAD

**Issue by avdata99** [datopian/ckanext-datajson#1]
Tests for [154](https://github.com/GSA/datagov-ckan-multi/issues/154).  
_CI should be configured to run automated tests for both CKAN 2.3 and 2.8 on commit_

### Tasks

* [x] define an environment for CI
* [x] test every commit at CKAN 2.8
* [x] test every commit at CKAN 2.3 (check if we really need this)

### Analysis

Documentation to test extensions at CKAN 2.8 [here](https://docs.ckan.org/en/2.8/extensions/testing-extensions.html).  
Analyze [the notes about testing this extension](https://github.com/avdata99/ckanext-datajson/blob/datagov/testing.md), test the process an upgrade it to work with CKAN 2.8
